#!/system/bin/sh

# Set first parameter to profile
profile=$1

# Function to apply ramdisk style settings
function write() {
    echo -n $2 > $1
}


Balance() {
	echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 
    echo "960000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq 
    echo "1401000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 
    echo "54 960000:85 1094400:75 1248000:80 1401000:99" > /sys/devices/system/cpu/cpufreq/interactive/target_loads 
    echo "120000" > /sys/devices/system/cpu/cpufreq/interactive/timer_slack 
    echo "1094400" > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq 
    echo "70000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate 
    echo "20000 1094400:120000" > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay 
    echo "85" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
    echo "45000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/max_freq_hysteresis 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/ignore_hispeed_on_notif 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/boost 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/fast_ramp_down 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/align_windows 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/use_migration_notif 
    echo 1 > /sys/devices/system/cpu/cpufreq/interactive/use_sched_load 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/boostpulse_duration 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/io_is_busy 
    echo 1 > /sys/module/cpu_boost/parameters/input_boost_enabled 
    echo "0:1094400 1:1094400 2:1248000 3:0" > /sys/module/cpu_boost/parameters/input_boost_freq 
    echo "120"  > /sys/module/cpu_boost/parameters/input_boost_ms 
    echo cfq > /sys/block/mmcblk0/queue/scheduler 
	# GPU
	echo simple_ondemand > /sys/class/kgsl/kgsl-3d0/devfreq/governor 
	echo "523200000" > /sys/class/kgsl/kgsl-3d0/devfreq/max_freq 
	echo "523200000" > /sys/class/kgsl/kgsl-3d0/max_gpuclk 
}

Performance() {
	echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 
    echo "960000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq 
    echo "1497600" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 
    echo "80 960000:33 1094400:50 1248000:70 1401000:90 1497600:98" > /sys/devices/system/cpu/cpufreq/interactive/target_loads 
	echo "85" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay 
	echo "40000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate 
	echo "1248000" > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq 
	echo "-1" > /sys/devices/system/cpu/cpufreq/interactive/timer_slack 
    echo "50000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time 
    echo "166667" > /sys/devices/system/cpu/cpufreq/interactive/max_freq_hysteresis 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/boost 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/powersave_bias
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/align_windows 
    echo 0 > /sys/module/cpu_boost/parameters/boost_ms
    echo 1 > /sys/module/cpu_boost/parameters/input_boost_enabled 
    echo "0:1094400 1:1094400 2:1094400 3:1094400" > /sys/module/cpu_boost/parameters/input_boost_freq 
    echo "40"  > /sys/module/cpu_boost/parameters/input_boost_ms 
    echo cfq > /sys/block/mmcblk0/queue/scheduler 
	# GPU
	echo msm-adreno-tz > /sys/class/kgsl/kgsl-3d0/devfreq/governor 
	echo "598000000" > /sys/class/kgsl/kgsl-3d0/devfreq/max_freq 
	echo "598000000" > /sys/class/kgsl/kgsl-3d0/max_gpuclk 
}

Battery() {
	echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 
    echo "960000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq 
    echo "1248000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 
    echo "64 960000:92 1094400:85 1248000:99" > /sys/devices/system/cpu/cpufreq/interactive/target_loads 
    echo "-1" > /sys/devices/system/cpu/cpufreq/interactive/timer_slack 
    echo "960000" > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq 
    echo "75000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate 
    echo "470000 960000:120000" > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay 
    echo "80" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
    echo "65000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/max_freq_hysteresis 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/ignore_hispeed_on_notif 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/boost 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/fast_ramp_down 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/align_windows 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/use_migration_notif 
    echo 1 > /sys/devices/system/cpu/cpufreq/interactive/use_sched_load 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/boostpulse_duration 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/io_is_busy 
    echo 1 > /sys/module/cpu_boost/parameters/input_boost_enabled 
    echo "0:960000 1:960000 2:1094400 3:0" > /sys/module/cpu_boost/parameters/input_boost_freq 
    echo "100"  > /sys/module/cpu_boost/parameters/input_boost_ms 
    echo cfq > /sys/block/mmcblk0/queue/scheduler 
	# GPU
	echo powersave > /sys/class/kgsl/kgsl-3d0/devfreq/governor 
	echo "523200000" > /sys/class/kgsl/kgsl-3d0/devfreq/max_freq 
	echo "523200000" > /sys/class/kgsl/kgsl-3d0/max_gpuclk 
}

Gaming() {
	echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 
    echo "960000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq 
    echo "1497600" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 
    echo "99" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
    echo "40000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/max_freq_hysteresis 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/ignore_hispeed_on_notif 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/boost 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/fast_ramp_down 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/align_windows 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/use_migration_notif 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/use_sched_load 
    echo 0 > /sys/devices/system/cpu/cpufreq/interactive/boostpulse_duration 
    echo cfq > /sys/block/mmcblk0/queue/scheduler 
	# GPU
	echo msm-adreno-tz > /sys/class/kgsl/kgsl-3d0/devfreq/governor 
	echo "598000000" > /sys/class/kgsl/kgsl-3d0/devfreq/max_freq 
	echo "598000000" > /sys/class/kgsl/kgsl-3d0/max_gpuclk 
}
#
echo "64" > /sys/block/mmcblk0/queue/read_ahead_kb 
echo > 0 /sys/module/msm_performance/parameters/touchboost
echo > "270000000" /sys/class/kgsl/kgsl-3d0/devfreq/min_freq
#
# Profile Selection
if [ $profile == 'balance' ]
then
	Balance
elif [ $profile == 'performance' ]
then
	Performance
elif [ $profile == 'battery' ]
then
	Battery
elif [ $profile == 'gaming' ]
then
	Gaming
fi	
	
